create table "public"."rooms" (
    "id" bigint generated by default as identity not null,
    "createdAt" timestamp with time zone default now(),
    "providerId" text,
    "name" text,
    "creatorId" text
);


alter table "public"."rooms" enable row level security;

CREATE UNIQUE INDEX rooms_name_key ON public.rooms USING btree (name);

CREATE UNIQUE INDEX rooms_pkey ON public.rooms USING btree (id);

CREATE UNIQUE INDEX "rooms_providerId_key" ON public.rooms USING btree ("providerId");

alter table "public"."rooms" add constraint "rooms_pkey" PRIMARY KEY using index "rooms_pkey";

alter table "public"."rooms" add constraint "rooms_name_key" UNIQUE using index "rooms_name_key";

alter table "public"."rooms" add constraint "rooms_providerId_key" UNIQUE using index "rooms_providerId_key";

create policy "Enable read access for all users"
on "public"."rooms"
as permissive
for select
to public
using (true);



